# Generated by Django 2.2.5 on 2019-10-09 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cobra_wrapper', '0002_cobrametabolitechange_cobramodelchange_cobrareactionchange'),
        ('biobricks', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packgene',
            old_name='reaction',
            new_name='gene',
        ),
        migrations.RenameField(
            model_name='packmetabolite',
            old_name='reaction',
            new_name='metabolite',
        ),
        migrations.CreateModel(
            name='PackComputationalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobra_wrapper.CobraModel')),
                ('model_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackBiobrick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biobrick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobricks.Biobrick')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
