language: python
python: "3.6"
dist: xenial
sudo: required

git:
  depth: 3

branches:
  only:
    - master

addons:
  apt:
    packages:
      - rabbitmq-server

service:
  - postgresql
  - rabbitmq

install:
  - pip3 install -r requirements.txt

before_script:
  - cd backend
  - cp backend/config.py.example backend/config.py
  - env PYTHONOPTIMIZE=1 celery worker -l info -A backend -Q cobra_results &> celery_backend.log &
  - (cd cobra_wrapper/remote &&
    env PYTHONOPTIMIZE=1 celery worker -l info -A cobra_computation -Q cobra_feeds &> celery_computation.log &)
  - psql -c 'create database igm_backend;' -U postgres
  - echo "STATIC_ROOT = '/tmp/static'" >> backend/settings.py

script:
  - flake8
  - python3 manage.py fix_pymysql
  - python3 manage.py migrate
  - python3 manage.py migrate_to_psql
  - python3 manage.py collectstatic

after_script:
  - kill %1 %2
  - cat celery_backend.log
  - cat cobra_wrapper/remote/celery_computation.log

cache:
  pip: true
