language: python
python: "3.6"
dist: xenial
sudo: required

git:
  depth: 3

branches:
  only:
    - master

env:
  global:
    - ES_VERSION=2.4.6
    - ES_DOWNLOAD_URL=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.deb
    - ES_DEB_PATH=$HOME/.cache/elasticsearch/elasticsearch-${ES_VERSION}.deb

addons:
  apt:
    packages:
      - rabbitmq-server

service:
  - elasticsearch
  - rabbitmq

before_install:
  - \[ -f ${ES_DEB_PATH} \] || curl --create-dirs -Oo ${ES_DEB_PATH} ${ES_DOWNLOAD_URL}
  - sudo dpkg -i --force-confnew elasticsearch-${ES_VERSION}.deb && sudo service elasticsearch restart

install:
  - pip3 install -r requirements.txt

before_script:
  - cd backend
  - env PYTHONOPTIMIZE=1 celery worker -l info -A backend -Q cobra_results &> celery_backend.log &
  - (cd cobra_wrapper/remote &&
    env PYTHONOPTIMIZE=1 celery worker -l info -A cobra_computation -Q cobra_feeds &> celery_computation.log &)
  - sleep 5  # Leave time for elasticsearch and celery workers to start
  - echo "STATIC_ROOT = '/tmp/static'" >> backend/settings.py

script:
  - flake8
  - python3 manage.py fix_pymysql
  - python3 manage.py migrate
  - python3 manage.py collectstatic

after_script:
  - kill %1 %2
  - cat celery_backend.log
  - cat cobra_wrapper/remote/celery_computation.log

cache:
  pip: true
  directories:
    - $HOME/.cache/elasticsearch
