version: '3'
services:
    main:
        build: .
        ports:
            - "8000:8000"
        environment:
            USE_MYSQL: "TRUE"
            PYTHONUNBUFFERED: 1
        command: python manage.py runserver
        links:
            - mysql
            - elasticsearch
        volumes:
            - "./backend/:/app/"
    mysql:
        image: mysql:8.0.17
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
        environment:
            MYSQL_ROOT_PASSWORD: mysql_pwd
        ports:
            - "3306:3306"
    elasticsearch:
        image: elasticsearch:2.4.6
        ports:
            - "9200:9200"
