version: '3'
services:
    main:
        build: .
        ports:
            - "8000:8000"
        environment:
            PYTHONUNBUFFERED: 1
            CELERY_HOST: rabbitmq
        command: /run.sh 
        links:
            - mysql
            - rabbitmq
        volumes:
            - "./backend/:/app/"
    mysql:
        image: mysql:8.0.17
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
        environment:
            MYSQL_ROOT_PASSWORD: mysql_pwd
            MYSQL_DATABASE: igem_backend
            MYSQL_ROOT_HOST: "%" 
        volumes:
            - "./data:/docker-entrypoint-initdb.d"
        ports:
            - "3306:3306"
    rabbitmq:
        image: rabbitmq:3.7.17
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"
