version: '3'
services:
    main:
        build: .
        ports:
            - "8000:8000"
        environment:
            USE_MYSQL: "TRUE"
            MYSQL_HOST: mysql
            # USE_ELASTICSEARCH: "TRUE"
            # ELASTICSEARCH_HOST: elasticsearch
            CELERY_HOST: rabbitmq
            PYTHONUNBUFFERED: 1
        command: /run.sh 
        links:
            - mysql
            # - elasticsearch
            - rabbitmq
        volumes:
            - "./backend/:/app/"
    mysql:
        image: mysql:8.0.17
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
        environment:
            MYSQL_ROOT_PASSWORD: mysql_pwd
            MYSQL_DATABASE: igem_backend
            MYSQL_ROOT_HOST: "%" 
        volumes:
            - "./data:/docker-entrypoint-initdb.d"
        ports:
            - "3306:3306"
    # elasticsearch:
    #    image: elasticsearch:2.4.6
    #    ports:
    #        - "9200:9200"
    rabbitmq:
        image: rabbitmq:3.7.17
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"
