# Generated by Django 2.2.6 on 2019-10-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bNum', models.CharField(max_length=15, unique=True)),
                ('gene', models.CharField(max_length=15, unique=True)),
                ('rule', models.CharField(max_length=127)),
                ('reference', models.CharField(max_length=127)),
            ],
        ),
    ]
