# Generated by Django 2.2.6 on 2019-10-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulation',
            name='reference',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='rule',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
