# Generated by Django 2.2.6 on 2019-10-21 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeShareLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=127)),
                ('shared_type', models.CharField(max_length=15)),
                ('shared_id', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='ShareModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbml_content', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(blank=True, max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('reactions', models.TextField(blank=True)),
                ('metabolites', models.TextField(blank=True)),
                ('genes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
