# Generated by Django 2.2.3 on 2019-08-18 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobra_wrapper', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaboliteShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField()),
                ('can_edit', models.BooleanField()),
                ('metabolite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cobra_wrapper.CobraMetabolite')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReactionShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField()),
                ('can_edit', models.BooleanField()),
                ('metabolites', models.ManyToManyField(to='share.MetaboliteShare')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cobra_wrapper.CobraReaction')),
            ],
        ),
        migrations.CreateModel(
            name='ModelShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField()),
                ('can_edit', models.BooleanField()),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cobra_wrapper.CobraModel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reactions', models.ManyToManyField(to='share.ReactionShare')),
            ],
        ),
    ]
