# Generated by Django 2.2.3 on 2019-09-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20190908_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeShareLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=127)),
                ('shared_type', models.CharField(max_length=15)),
                ('shared_id', models.CharField(max_length=127)),
            ],
        ),
    ]
