# Generated by Django 2.2.5 on 2019-10-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biobrick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=127, unique=True)),
                ('description', models.TextField(null=True)),
                ('keywords', models.TextField(null=True)),
                ('uses', models.IntegerField(null=True)),
                ('url', models.URLField(null=True)),
            ],
        ),
    ]
