# Generated by Django 2.2.5 on 2019-10-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigg_id', models.CharField(max_length=127)),
                ('sbml_content', models.TextField()),
            ],
        ),
    ]
