# Generated by Django 2.2.3 on 2019-07-31 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CobraMetabolite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobra_id', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('formula', models.CharField(blank=True, default='', max_length=50)),
                ('charge', models.CharField(blank=True, default='', max_length=50)),
                ('compartment', models.CharField(blank=True, default='', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CobraReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobra_id', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('subsystem', models.CharField(blank=True, default='', max_length=50)),
                ('lower_bound', models.FloatField(default=0.0)),
                ('upper_bound', models.FloatField(blank=True, default=None, null=True)),
                ('objective_coefficient', models.FloatField(default=0.0)),
                ('coefficients', models.TextField(default='')),
                ('gene_reaction_rule', models.TextField(blank=True, default='')),
                ('metabolites', models.ManyToManyField(blank=True, to='cobra_wrapper.CobraMetabolite')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CobraModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobra_id', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('objective', models.CharField(default='', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reactions', models.ManyToManyField(blank=True, to='cobra_wrapper.CobraReaction')),
            ],
        ),
    ]
