# Generated by Django 2.2.5 on 2019-10-11 13:33

import cobra_wrapper.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CobraModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbml_content', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'model',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CobraModelChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('add_reaction', 'add_reaction'), ('del_reaction', 'del_reaction'), ('sbml_content', 'sbml_content'), ('name', 'name'), ('objective', 'objective')], max_length=50)),
                ('pre_info', models.CharField(blank=True, max_length=600)),
                ('new_info', models.CharField(blank=True, max_length=600)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='cobra_wrapper.CobraModel')),
            ],
            options={
                'verbose_name': 'model_change',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='CobraFva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True)),
                ('reaction_list', models.TextField()),
                ('loopless', models.BooleanField(default=False)),
                ('fraction_of_optimum', models.FloatField(default=1.0)),
                ('pfba_factor', models.BooleanField(blank=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.UUIDField(blank=True, default=None, null=True)),
                ('result', models.TextField(blank=True, validators=[cobra_wrapper.models.validate_json_str_or_blank_str])),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fva_list', to='cobra_wrapper.CobraModel')),
            ],
            options={
                'verbose_name': 'fva',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CobraFba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.UUIDField(blank=True, default=None, null=True)),
                ('result', models.TextField(blank=True, validators=[cobra_wrapper.models.validate_json_str_or_blank_str])),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fba_list', to='cobra_wrapper.CobraModel')),
            ],
            options={
                'verbose_name': 'fba',
                'ordering': ['-start_time'],
            },
        ),
    ]
