# Generated by Django 2.2.5 on 2019-10-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobra_wrapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrafba',
            name='deleted_genes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cobrafva',
            name='deleted_genes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cobrafba',
            name='desc',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='cobrafva',
            name='desc',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='cobrafva',
            name='pfba_factor',
            field=models.FloatField(default=1.0),
        ),
    ]
