# Generated by Django 2.2.3 on 2019-07-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobra_wrapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cobrametabolite',
            old_name='base',
            new_name='identifier',
        ),
        migrations.RenameField(
            model_name='cobramodel',
            old_name='base',
            new_name='identifier',
        ),
        migrations.RenameField(
            model_name='cobrareaction',
            old_name='base',
            new_name='identifier',
        ),
        migrations.AddField(
            model_name='cobrametabolite',
            name='charge',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='cobramodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cobrareaction',
            name='objective_coefficient',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cobrametabolite',
            name='compartment',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='cobrametabolite',
            name='formula',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='cobrametabolite',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cobrareaction',
            name='coefficients',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cobrareaction',
            name='gene_reaction_rule',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cobrareaction',
            name='lower_bound',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cobrareaction',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cobrareaction',
            name='subsystem',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cobrareaction',
            name='upper_bound',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
