# Generated by Django 2.2.3 on 2019-08-16 09:52

import cobra_wrapper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobra_wrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobrareaction',
            name='coefficients',
            field=models.TextField(blank=True, default='', validators=[cobra_wrapper.models.validate_coefficients_space_splited_text]),
        ),
    ]
