# Generated by Django 2.2.4 on 2019-08-13 11:44

import cobra_wrapper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobra_wrapper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobrafba',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='cobrafva',
            name='task_id',
        ),
        migrations.AddField(
            model_name='cobrafba',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cobrafba',
            name='result',
            field=models.TextField(blank=True, default='', validators=[cobra_wrapper.models.validate_json_str_or_blank_str]),
        ),
        migrations.AddField(
            model_name='cobrafva',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cobrafva',
            name='result',
            field=models.TextField(blank=True, default='', validators=[cobra_wrapper.models.validate_json_str_or_blank_str]),
        ),
    ]
