# Generated by Django 2.2.3 on 2019-07-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobra_wrapper', '0002_auto_20190720_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobrametabolite',
            name='charge',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cobrametabolite',
            name='compartment',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cobrametabolite',
            name='formula',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cobrareaction',
            name='upper_bound',
            field=models.FloatField(default=None, null=True),
        ),
    ]
