# Generated by Django 2.2.5 on 2019-10-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobra_wrapper', '0003_auto_20191016_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrafba',
            name='ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cobrafva',
            name='ok',
            field=models.BooleanField(default=False),
        ),
    ]
