# Generated by Django 2.2.3 on 2019-07-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobra_wrapper', '0003_auto_20190720_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobrametabolite',
            name='charge',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cobrametabolite',
            name='compartment',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cobrareaction',
            name='upper_bound',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
