# Generated by Django 2.2.3 on 2019-07-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobra_wrapper', '0004_auto_20190720_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobramodel',
            name='objective',
            field=models.CharField(default='', max_length=50),
        ),
    ]
