# Generated by Django 2.2.6 on 2019-10-20 12:15

import cobra_wrapper.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobra_wrapper', '0005_auto_20191018_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobraRgeFba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=600)),
                ('deleted_genes', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.UUIDField(blank=True, default=None, null=True)),
                ('result', models.TextField(blank=True, validators=[cobra_wrapper.models.validate_json_str_or_blank_str])),
                ('ok', models.BooleanField(default=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rgefba_list', to='cobra_wrapper.CobraModel')),
            ],
            options={
                'verbose_name': 'rge_fba',
                'ordering': ['-start_time'],
            },
        ),
    ]
