# Generated by Django 2.2.6 on 2019-10-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobra_wrapper', '0006_cobrargefba'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobramodel',
            name='genes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cobramodel',
            name='metabolites',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cobramodel',
            name='reactions',
            field=models.TextField(blank=True),
        ),
    ]
