# Generated by Django 2.2.6 on 2019-10-30 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobra_wrapper', '0007_auto_20191021_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobraBiobrick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=127, unique=True)),
                ('cobra_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobra_wrapper.CobraModel')),
            ],
            options={
                'verbose_name': 'model_biobrick',
            },
        ),
    ]
