# Generated by Django 2.2.3 on 2019-07-30 13:12

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('bigg_database', '0004_auto_20190721_2206'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gene',
            constraint=models.CheckConstraint(check=models.Q(rightpos__gte=django.db.models.expressions.F('leftpos')), name='right_gte_left'),
        ),
        migrations.AddConstraint(
            model_name='modelreaction',
            constraint=models.CheckConstraint(check=models.Q(upper_bound__gte=django.db.models.expressions.F('lower_bound')), name='upper_gte_lower'),
        ),
    ]
