# Generated by Django 2.2.3 on 2019-07-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigg_database', '0004_auto_20190721_2206'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modelmetabolite',
            unique_together={('model', 'metabolite')},
        ),
        migrations.AlterUniqueTogether(
            name='modelreaction',
            unique_together={('model', 'reaction')},
        ),
        migrations.AlterUniqueTogether(
            name='reactiongene',
            unique_together={('reaction', 'gene')},
        ),
        migrations.AlterUniqueTogether(
            name='reactionmetabolite',
            unique_together={('reaction', 'metabolite')},
        ),
    ]
