# Generated by Django 2.2.3 on 2019-07-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigg_database', '0005_auto_20190730_2112'),
        ('bigg_database', '0005_auto_20190730_2001'),
    ]

    operations = [
    ]
