# Generated by Django 2.2.3 on 2019-08-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigg_database', '0006_merge_20190730_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metabolite',
            name='name',
            field=models.CharField(max_length=511),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_string',
            field=models.CharField(max_length=7000),
        ),
    ]
