# Generated by Django 2.2.3 on 2019-08-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigg_database', '0007_auto_20190801_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelreaction',
            name='gene_reaction_rule',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reactiongene',
            name='gene_reaction_rule',
            field=models.TextField(),
        ),
    ]
