# Generated by Django 2.2.4 on 2019-08-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigg_database', '0008_auto_20190802_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
