# Generated by Django 2.1.7 on 2019-07-20 08:12

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigg_id', models.CharField(max_length=127, unique=True)),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Metabolite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigg_id', models.CharField(max_length=127, unique=True)),
                ('name', models.CharField(max_length=127)),
                ('formulae', models.CharField(max_length=127)),
                ('charges', models.IntegerField()),
                ('database_links', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigg_id', models.CharField(max_length=127, unique=True)),
                ('name', models.CharField(max_length=127)),
                ('compartments', models.CharField(choices=[('c', 'cytosol'), ('e', 'extracellular space'), ('p', 'periplasm'), ('m', 'mitochondria'), ('x', 'peroxisome/glyoxysome'), ('r', 'endoplasmic reticulum'), ('v', 'vacuole'), ('n', 'nucleus'), ('g', 'golgi apparatus'), ('u', 'thylakoid'), ('l', 'lysosome'), ('h', 'chloroplast'), ('f', 'flagellum'), ('s', 'eyespot'), ('im', 'intermembrane space of mitochondria'), ('cx', 'carboxyzome'), ('um', 'thylakoid membrane'), ('cm', 'cytosolic membrane'), ('i', 'i')], max_length=127)),
                ('version', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='ModelMetabolite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism', models.CharField(max_length=127)),
                ('metabolite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigg_database.Metabolite')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigg_database.Model')),
            ],
        ),
        migrations.CreateModel(
            name='ModelReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism', models.CharField(max_length=127)),
                ('lower_bound', models.FloatField()),
                ('upper_bound', models.FloatField()),
                ('subsystem', models.CharField(max_length=127)),
                ('gene_reaction_rule', models.CharField(max_length=127)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigg_database.Model')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigg_id', models.CharField(max_length=127, unique=True)),
                ('name', models.CharField(max_length=127)),
                ('reaction_string', models.CharField(max_length=1023)),
                ('pseudoreaction', models.BooleanField()),
                ('database_links', jsonfield.fields.JSONField(default=dict)),
                ('models', models.ManyToManyField(through='bigg_database.ModelReaction', to='bigg_database.Model')),
            ],
        ),
        migrations.CreateModel(
            name='ReactionMetabolite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stoichiometry', models.IntegerField()),
                ('metabolite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigg_database.Metabolite')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigg_database.Reaction')),
            ],
        ),
        migrations.AddField(
            model_name='modelreaction',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigg_database.Reaction'),
        ),
        migrations.AddField(
            model_name='metabolite',
            name='models',
            field=models.ManyToManyField(through='bigg_database.ModelMetabolite', to='bigg_database.Model'),
        ),
        migrations.AddField(
            model_name='metabolite',
            name='reactions',
            field=models.ManyToManyField(through='bigg_database.ReactionMetabolite', to='bigg_database.Reaction'),
        ),
        migrations.AddField(
            model_name='gene',
            name='models',
            field=models.ManyToManyField(to='bigg_database.Model'),
        ),
    ]
