# Generated by Django 2.2.3 on 2019-07-21 14:06

import bigg_database.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigg_database', '0003_auto_20190721_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metabolite',
            name='formulae',
            field=bigg_database.fields.JSONField(max_length=127),
        ),
    ]
